=== saikirandodle/NRD_LAB/ex6/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="publisher" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="year" type="xs:gYear"/>
                        </xs:sequence>

                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== saikirandodle/NRD_LAB/ex6/bookstore-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">

    <book id="B101">
        <title>XML Fundamentals</title>
        <author>John Smith</author>
        <publisher>Tech Publications</publisher>
        <price>450.50</price>
        <year>2024</year>
    </book>

    <book id="B102">
        <title>Learning XSD</title>
        <author>Jane Doe</author>
        <publisher>Code House</publisher>
        <price>550.00</price>
        <year>2023</year>
    </book>

</bookstore>
